#!/bin/zsh -li

set -euo pipefail

success=true

# ~/.* ファイルが ~/projects/doffiles/.* へのシンボリックリンクか
# 一例として .vimrc を調査
if [ "$(readlink ~/.vimrc)" != "$HOME/projects/dotfiles/.vimrc" ]; then
  echo '. から始まるファイルのシンボリックリンクが作成されていません' >&2
  success=false
fi

# .zshrc が読み込まれているか
# 一例として success/warning/error コマンドの調査
if ! (type success && type warning && type error) >/dev/null; then
  echo '.zshrc が読み込まれていません' >&2
  success=false
fi

$success
