name: Install Test

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: cat install.sh | sh
      - name: Test
        run: ~/projects/dotfiles/test
